#ifndef CMDDEF_H
#define CMDDEF_H
#define GET "GET"
#define HANDIN "HANDIN"
//验证用户
#define AUTHOR "AUTHORISE"
//退出登陆时标志
#define LOGOUT "LOGOUT"
//检测登陆
#define CHECK "CHECK"
#define LOGIN "LOGIN"

#define POSI_INFO "POSI_INFO"
#define GOOD_INFO "GOOD_INFO"
#define CUR_STATUS "CUR_STATUS"
#define USR_EXCEPT "USR_EXCEPT"

#define DIARY "DIARY"
#define DIARIES "DIARIES"
#define DIA_CON "DIARY_CONTENT"

#define THIS_MONTH_THROUGHPUT "THIS_MONTH_THROUGHPUT"
#define NEXT_MONTH_THROUGHPUT   "NEXT_MONTH_THROUGHPUT"
#define COMPANY_BUSY_RANK   "COMPANY_BUY_RANK"
#define GOOD_WASTAGE    "GOOD_WASTAGE"

#define INPUTTABLE "INPUTTABLE"
#define OUTPUTTABLE "OUTPUTTABLE"
#define CHECKTABLE "CHECKTABLE"

#define NOTHING "NOTHING"
#define OK "OK"
#define EXCEP_STRUCT_SIZE 8
#define DIARY_STRUCT_SIZE 4
#define OVERTIME "OVERTIME"
#endif // CMDDEF_H
